### ISSUE TITLE
Tooling/scripts/etc. for log analysis

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/cuizinart#100]
We should start thinking about log analysis - analyzing what users are querying about. Ultimately, it'd be awesome to have some type of dashboard... but as a start, we should write scripts to answer basic questions, e.g.

+ how many users
+ how many queries (per day, per week, etc.)
+ ...

**Comment by gauchm** [comment]
Cleanup -- closing as inactive.
We already have a few simple scripts to analyze #requests, etc. for CaSPAr. Currently not worth the effort on Cuizinart since there aren't many requests to begin with.
