### ISSUE TITLE
JSON string for SLURM backend

### ISSUE THREAD

**Issue by julemai** [gwf-uwaterloo/Cuizinart#11]
@gauchm Could you please redirect the transfers of the files containing the JSON strings to `/project/6008034/cuizinart/OUTBOX/`. It is so far `/project/6008034/WRF-REQUEST/OUTBOX/` due to historical reasons. Thanks!

**Comment by julemai** [comment]
I have finally Globus setup for the SLURM backend. Therefore, we need to make sure that the `user_id` is actually the Globus ID. I think it would be helpful if you could change the field on the website from "User ID" to "Globus ID" and set the description "Enter User ID" to "Globus ID, e.g., foo@globusid.org".

I will check on the backend if the Globus ID is valid and email the user in case it isn't.

**Comment by gauchm** [comment]
@julemai are you sure the json files should got to `OUTBOX` and not `INBOX`?

**Comment by julemai** [comment]
@gauchm yes, INBOX!!! :)

**Comment by gauchm** [comment]
Updated the path with 6f5fde6 in slurm-json. 
Didn't create a PR yet so we can merge this together with the second part of this issue.

**Comment by julemai** [comment]
Sounds good! Thanks!

**Comment by julemai** [comment]
@gauchm You are the only one who has permissions to write to the `INBOX`. We need to keep that in mind in case there's gonna be another user sending this file over.

**Comment by gauchm** [comment]
Done with #15
