### ISSUE TITLE
Upload GeoJSON fails

### ISSUE THREAD

**Issue by julemai** [gwf-uwaterloo/cuizinart#152]
The GeoJSON file upload does not seem to work (at least on CaSPAr). I tried with a file with the following content:
```
{"geometry": {"coordinates": [[[-72.489613, 45.963127], [-72.236013, 45.822985], [-72.374656, 45.709168], [-72.693627, 45.863138], [-72.489613, 45.963127]]], "type": "Polygon"}, "properties": {}, "type": "Feature"}
```

This was copied from the email users receive after successfully submitting a request. That is the exact geoJSON string send to the backend.

Not sure why this does not work. An example of how this needs to be formatted would be useful.

The error message is "Parsing error".

**Comment by gauchm** [comment]
The string you posted needs to be wrapped in a FeatureCollection, which contains a list of "features". Thus, at the very least, it must look like this:
```json
{
  "type": "FeatureCollection",
  "features": [
    {
      "geometry": {
        "coordinates": [
          [
            [-72.489613, 45.963127],
            [-72.236013, 45.822985],
            [-72.374656,  45.709168],
            [-72.693627,45.863138],
            [-72.489613,  45.963127]
          ]
        ],
        "type": "Polygon"
      },
      "properties": {},
      "type": "Feature"
    }
  ]
}
```

You can use online editors like https://geojson.io, https://vector.rocks, or https://geoman.io/geojson-editor to create valid GeoJSON files.

**Comment by julemai** [comment]
Awesome! Thanks a lot. I've added all that information now to the documentation:
https://github.com/julemai/CaSPAr/wiki/How-to-get-started-and-download-your-first-data
