### ISSUE TITLE
Support Products that span multiple NetCDF files

### ISSUE THREAD

**Issue by gauchm** [gwf-uwaterloo/Cuizinart#21]
For starters, support products that are partitioned along the time domain.
E.g., file1.nc ->2000-2010, file2.nc -> 2010-2019, ...

We might need to add a metadata field that tells us if (and how) a product spans across multiple NetCDF files.

**Comment by julemai** [comment]
I organize that as follows in CaSPAr:
- every product has a subfolder named exactly as the product
- this folder contains all files for this product
- filename indicate the first time step (issue date) in format YYYYMMDDHH.nc
- NetCDF files have a global attribute called `:product` that is set to be the product name (just to double check during processing that files haven't been messed up)

Hence there's no need to specify that product spans over multiple files. This is assumed to be the regular case anyway. For processing just all files in the folder are considered.

**Comment by gauchm** [comment]
Done.
