### ISSUE TITLE
E-Mail Notification for Completed Jobs

### ISSUE THREAD

**Issue by gauchm** [gwf-uwaterloo/Cuizinart#29]
Notify users via email when a job completes/fails (replacing the current front-end NetCDF download)

**Comment by gauchm** [comment]
The most basic implementation of this is simple: The Slurm-backend already sends emails itself, and for the PySpark-backend just wait for the job to complete and then send out an email.

Looking ahead though, I believe we should think a bit more about this. 
Once we implement users/requests in the metadata database, we'll want the Cuizinart backend to store job completion metadata in the database. So we'll need the slicing-backends to call back after executing a job. @julemai: How does the Slurm backend currently do this? E.g., do you already have a fixed format of returning result metadata? If so, we could take that over for the PySpark slicer.

Proposal:
![request-sequence](https://user-images.githubusercontent.com/15731649/54573036-d48bf000-49c0-11e9-8b4b-bd5b7bd3c65c.png)

Any thoughts/comments?

**Comment by julemai** [comment]
Right now I don’t do anything because I don’t have a database to report to. I however have setup Globus completely on the backend now and send out the emails with download links etc. I will send you tomorrow the JSON string we report back to the DB in CaSPAr. Don’t have connection to that atm

**Comment by gauchm** [comment]
Done with #32.
