### ISSUE TITLE
Clean up production list of products

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/cuizinart#52]
Now that we've got a live, publicly-accessible server...

From @julemai 

> But we should clean-up the list of products a bit. I don’t know what “precipitation”, “minimum temperature” and “maximum temperature” is. We should either remove them or give them a better title

> And the RDPS was only a test product. We should remove that completely.

**Comment by gauchm** [comment]
Done. Removed products that are not (yet) on Graham.

**Comment by lintool** [comment]
Nice, thanks!
