### ISSUE TITLE
Discussion: UI revamp

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/cuizinart#53]
I quite like the design of https://gwf-uwaterloo.github.io/wamedex/

In particular, put everything in a (re-sizeable) sidebar, which maximizes the map area - makes the look pretty clean.

Thoughts?

**Comment by gauchm** [comment]
Generally I agree. I'm still unsure if an Accordion for products would be suitable here, too. 

The globus id, shapefile upload and (if we have it) backend selection are product-independent, so they should be outside the collapsible accordions. That might not leave a lot of space for a product list in the same sidebar.

**Comment by lintool** [comment]
> Generally I agree. I'm still unsure if an Accordion for products would be suitable here, too.

I think keeping products as a dropdown.

> The globus id, shapefile upload and (if we have it) backend selection are product-independent, so they should be outside the collapsible accordions. That might not leave a lot of space for a product list in the same sidebar.

Globus id is associated with a profile, right? So should be part of a user profile page?
In general, I think the text on the sidebar is a bit too large and chunky.
We can make the sidebar sizeable?

**Comment by gauchm** [comment]
Yeah, that should work. I'll try it out and see how it looks.

**Comment by gauchm** [comment]
Done.
