### ISSUE TITLE
Prod vs. dev

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/cuizinart#54]
Now that we're moving into production, we should probably separate a prod vs. dev branch?

On the prod, we should only have products that actually exist (no test products), using graham only - let's save PySpark for the dev branch.

Concrete todo: separate current code status into prod and dev branch?

I guess we have two choices - prod is master or dev is master? Thoughts @gauchm

**Comment by gauchm** [comment]
For the available products: that's unrelated to the codebase. It's just what we put in the database. So the first thing would be to have a dev and a prod deployment.
But nevertheless I agree we should have a dev and prod branch. This allows us to deactivate PySpark in prod.

I don't really have a preference about which is master, let's do prod==master?

**Comment by lintool** [comment]
Actually, I think dev==master is better. Rationale:

(1) If dev==master, to deploy new features to prod, we simply merge master into prod and remove all the extra testing stuff.
(2) If prod==master, to merge dev features to prod, we gotta cherry pick the features to merge into master.

Seems like removing testing stuff is easier than picking out features? So that would suggest (1) is better?

Thoughts?

**Comment by gauchm** [comment]
Okay, sounds good

**Comment by gauchm** [comment]
With #60, we have a dev instance running on tuna.cs.uwaterloo.ca:5000 and production on tuna.cs.uwaterloo.ca

**Comment by gauchm** [comment]
Closing for now. Still not optimal as dev instance is not exactly the same setup as production, but okay for now.
