### ISSUE TITLE
Disclaimer message  

### ISSUE THREAD

**Issue by bhaleka** [gwf-uwaterloo/cuizinart#58]
We need to think about having a disclaimer message that users  agree to before downloading the data e.g "The data provided has been obtained from a variety of sources and is provided as a public service by the University of Waterloo.  It is provided by the University of Waterloo with an open license on an “AS IS” basis without any warranty or representation, express or implied, as to its accuracy or completeness"
Examples are
https://www.nodc.noaa.gov/about/disclaimer.html
https://climate.com/legal/disclaimer

Also include the  Terms and Conditions of GWF Data Use as outlined on Pages 18-19 of the Data Policy https://gwf.usask.ca/documents/GWF_Data_Policy_March-4-2019-Final.pdf

**Comment by julemai** [comment]
Good idea. I could distribute this disclaimer also when people download the data or attach it to the email they receive containing the download link.

**Comment by gauchm** [comment]
We might also need some privacy note as we store emails and track user requests.

**Comment by julemai** [comment]
Example for Privacy statement from ECMWF ([link](https://www.ecmwf.int/en/privacy))

**Comment by gauchm** [comment]
Done.
