### ISSUE TITLE
UI refinement suggestion: variables

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/cuizinart#61]
For variables selection, do something like what GitHub does?

<img width="416" alt="Screen Shot 2019-04-25 at 7 52 39 PM" src="https://user-images.githubusercontent.com/313837/56775143-cb4a2c00-6793-11e9-8503-2ff12d61268a.png">

**Comment by gauchm** [comment]
[Note to self: https://sharlaan.github.io/example4]

Some thoughts on this:
- @julemai maybe you have some insight here: Do people more likely (a) know what they want and just need quick access to it or (b) do they need to browse through the list to discover what's available?
In case of (a), this suggestion would be great, in case of (b) this would make it harder to browse through the list.
- We have more information that we currently display, e.g. the unit. We could accommodate (a) and (b) by having the suggested GitHub-style search plus an icon to popup a table with all information. (https://material-ui.com/demos/tables/#sorting-amp-selecting)

**Comment by bhaleka** [comment]
I believe it is a combination of both.  Some researchers know data/variables they are looking for and some researchers want to know what data/variables are available, that being said they will also want quick access too

**Comment by julemai** [comment]
I think most of the people are from group a). All of b) will ask for an API something ner or later.

**Comment by gauchm** [comment]
#66 introduces a selection similar to the proposed.

**Comment by gauchm** [comment]
Done with #66.
