### ISSUE TITLE
UI sidebar refinements

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/cuizinart#64]
@gauchm I think there are some minor placement issues with the sidebar. See below:
(not urgent)

**IMAGE 1**
<img width="337" alt="Screen Shot 2019-04-26 at 11 07 49 AM" src="https://user-images.githubusercontent.com/313837/56817526-c2993a80-6813-11e9-86b1-5f5c3cd4e8e4.png">

**IMAGE 2**
<img width="317" alt="Screen Shot 2019-04-26 at 11 08 02 AM" src="https://user-images.githubusercontent.com/313837/56817533-c62cc180-6813-11e9-894f-480bad011dda.png">

+ In **IMAGE 1** there's a small gap between the sidebar and top navbar. This looks good. However, in **IMAGE 2** the sidebar disappears beneath the top navbar slightly... placement is off by a few pixels?
+ Collapse arrow for slidebar is weirdly placed... left shift by a few pixels?

**Comment by gauchm** [comment]
This happens when the sidebar content gets too long, so the overflow is scrollable.
With #66, this should no longer be an issue as we no longer display variables as a list.

**Comment by gauchm** [comment]
Done with #66, further improved with #82.
