### ISSUE TITLE
API intro to Julie

### ISSUE THREAD

**Issue by julemai** [gwf-uwaterloo/cuizinart#65]
@gauchm Please give Julie an intro on how to submit requests using an API

**Comment by gauchm** [comment]
1. Send an http POST request to tuna.cs.uwaterloo.ca/login with username and password as payload: `{email: <email>, password: <password>}`. The answer will contain an authentication token.
2. Send an http POST reqeust to tuna.cs.uwaterloo.ca/fetchResult with the request plus the token as payload: 
`{ variables: ['var1', 'var2', ...],
            window: [1, 2, ...],
            release: ['6:00', ...],
            product: 'prod1',
            backend: 'slurm',
            bounding_geom: [{'type': 'Feature', 'properties': {}, 'geometry': {'type': 'Polygon', 'coordinates': [[[-80, 42], [-81, 45], [-75, 45], [-75, 42], [-80, 42]]]}}],
            auth_token: '<token>' }`.

**Comment by julemai** [comment]
You're too fast...

I tried the first step (from command line):
```
curl --data "{email: juliane.mai@uwaterloo.ca, password: <my_password>}" http://tuna.cs.uwaterloo.ca/login
```

And it returns:
```
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.15.12</center>
</body>
</html>
```

Does that look right? I checked the credentials I used. they are working...

**Comment by gauchm** [comment]
`curl --data '{"email": "<email>", "password": "<pwd>"}' --request POST -H "Content-Type: application/json" https://tuna.cs.uwaterloo.ca/login` works for me.

**Comment by julemai** [comment]
Awesome. That works now.

I played around a bit with the second step (adding start and end time and Globus ID):
```
curl --data '{"variables": ["T2"], "window": [], "release": [], "product": "ctl-wrf-wca", "backend": "slurm", "bounding_geom": [{"type": "Feature", "properties": {}, "geometry": {"type": "Polygon", "coordinates": [[[-80, 42], [-81, 45], [-75, 45], [-75, 42], [-80, 42]]]}}], "auth_token": "<token-from-above>","start_time": "2000-10-09", "end_time": "2000-10-17","globus_id": "julemai@computecanada.ca"}' --request POST -H "Content-Type: application/json" https://tuna.cs.uwaterloo.ca/fetchResult
```

And it made it straight through to Graham and is processing:
```
Request with id juliane.mai@uwaterloo.ca_1556308585 submitted successfully.
```

This is AMAZING!!!
