### ISSUE TITLE
Add new users

### ISSUE THREAD

**Issue by julemai** [gwf-uwaterloo/cuizinart#77]
Could we please add the following users:

Homa Kheyrollah Pour (h2kheyrollahpour@uwaterloo.ca)
Serghei Bocaniov (sbocaniov@uwaterloo.ca)
Jorge Andres Garcia Hernandez (ja4garciahernandez@uwaterloo.ca)
Xiang Huang (xiang.huang@uwaterloo.ca)
Mehdi Gharasoo (mehdi.gharasoo@uwaterloo.ca)
Mahyar Shafii (mshafiihassanabadi@uwaterloo.ca)
Ming Han (ming.han@uwaterloo.ca)
Hongren Shen (hongren.shen@uwaterloo.ca)

**Comment by gauchm** [comment]
Done.
