### ISSUE TITLE
Add Homa's datasets

### ISSUE THREAD

**Issue by julemai** [gwf-uwaterloo/cuizinart#78]
There are 3 new data products available on Graham now that need to be added to the Cuizinart frontend and DB (naming is case sensitive and needs to match otherwise the `product` is not found on Graham):

1. `era5` for Jan 01, 2002 to Dec 31, 2017
2. `modis-lst-mod_myd11_merged-monthly` from Aug 01, 2002 to Feb 28, 2017
3. `modis-lst-mod_myd11_merged-weekly` from Jan 01, 2002 - Dec 31, 2007

I will send the JSON string containing all information on variables, domain etc via slack to @gauchm and @Alex-Weatherhead. The JSON will only contain dates of one file. So only use the dates to see the temporal resolution but not to determine the period of data availability. I have listed the period of data availability above.

**Comment by gauchm** [comment]
Done.
