### ISSUE TITLE
UI minor nits

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/cuizinart#80]
<img width="382" alt="Screen Shot 2019-05-10 at 5 14 30 PM" src="https://user-images.githubusercontent.com/313837/57557176-1db84a80-7347-11e9-8999-c65ea19a4019.png">

+ It still looks to me that the text is too big...
+ The left arrow (collapse tab) placement looks odd...
+ If we make the font smaller, we can put the date range on the same line as heading - no need to say "available"; also let's do YYYY/MM/DD (slash instead of dash), so the date ranges looks better.
+ "Disclaimer and Privacy Notice": don't make all caps, make it much smaller, gray text. It's currently too much "in your face"; align it all the way bottom.

**Comment by gauchm** [comment]
Done with #82.
