### ISSUE TITLE
Add an about page

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/cuizinart#81]
Maybe linked from an icon on the top nav bar? A popover pages that provides a description of what cuizinart is, the team members (with pictures, etc.)

**Comment by julemai** [comment]
The description of the Cuizinart I use when I send out the download links to the people is something along the following lines:

Global Water Futures (GWF) data Cuizinart

email: gwf.cuizinart@uwaterloo.ca
webpage: https://gwf.usask.ca

GWF aims to position Canada as a global leader in water science for cold regions and will address the strategic needs of the Canadian economy in adapting to change and managing risks of uncertain water futures and extreme events. The GWF-Cuizinart to crop and subset geo-referenced data is developed at the University of Waterloo.

**Comment by gauchm** [comment]
Done with #83.
