### ISSUE TITLE
Potential datasets for Cuizinart 

### ISSUE THREAD

**Issue by bhaleka** [gwf-uwaterloo/cuizinart#85]
USask Modelling Wiki link (https://wiki.usask.ca/display/MDC) has  a number of datasets that modellers are using (potentially will be using). Some of these are publicly available 

Additional datasets recommended by researchers during the poster discussions. 
- Arctic high resolution DEM at  https://www.pgc.umn.edu/data/arcticdem/
- NDVI https://lpdaac.usgs.gov/products/mod13a3v006/

More to follow.

**Comment by gauchm** [comment]
Cleanup -- closing as inactive.
