### ISSUE TITLE
Open discussion: Metadata needed in the frontend

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/cuizinart#9]
What metadata do we need in the frontend? We need:
+ the domain (the geographic extent of the product)
+ available variables
+ time range

@julemai Correct me if I'm wrong, but by definition we're assuming that each product has a single domain? That is, if the domain has changed, then we'll treat it as a different product?

Additional question: Might the available variables change? I.e., within the same product, a variable is available for some time periods only.

**Comment by gauchm** [comment]
Given we want to port CaSPAr to Cuizinart at some point (#10), we need some more flexibility:
CaSPAr products are forecasts, so the "time range" gets a bit more involved. A product has 
* start/end date
* forecast window (measured in hours)
* issues (each day, multiple forecasts might be released: e.g. one at 12am and one at 12pm)

Static, non-forecast products won't have forecast windows and issues.

**Comment by gauchm** [comment]
Proposal for metadata database:
![cuizinart-db](https://user-images.githubusercontent.com/15731649/52814810-0f6dd180-306b-11e9-8a16-c9c6f3190a8f.jpg)

Please feel free to raise any suggestions/questions/concerns.

**Comment by lintool** [comment]
I don't think we need `available_graham` and `available_pyspark`? There will be two instances of the DB, right? So it's implicit - i.e., this is everything in _this_ particular instance of the tool?

**Comment by gauchm** [comment]
Good point. I'll remove it.

**Comment by lintool** [comment]
Also, according to @julemai 

>The list of variables is the list of all variables that are available at least at one time step. It might be that a variable was only available for 1 year. The user requests data for this variable but does not request this year of data. He/she would get an empty file back. This is CaSPAr (dynamic data).

This is reflected in the design above, right? The variable table will reference anything that appears at least once in the product, even if it only appears in one time step. This is fine and a reasonable design decision, but worth documenting somewhere.

What's `resolution` in the product table?

**Comment by gauchm** [comment]
Yes, this is reflected the way you explained it. If this is a common thing to happen (is it, @julemai ?), we could add start and end dates to variables, too. From my experience, effective dating usually makes things more complex, so if this is not happening too often I'd leave it as is.

`resolution` defines whether the data is daily/monthly/hourly/... so that we can offer the user the right type of time selector on the UI. E.g. if resolution is monthly, we shouldn't let the user select YYYY-MM-DD ranges but just YYYY-MM ranges.

**Comment by lintool** [comment]
Is `resolution` a feature of the product or of the variable? I.e., in a product, would all variables have the same resolution? this is probably a question from @julemai 

I like the current design in that we can just "hang" additional tables off products for further customization. So GWF might not have `horizon` and `issue'.

However, another alternative design is to just combine `horizon` and `issue' into a single `product_metadata` table with `(product_id, key, value)` - i.e., you can attach any arbitrary key-value pair to any product to further define it...

**Comment by julemai** [comment]
> Proposal for metadata database:
> ![cuizinart-db](https://user-images.githubusercontent.com/15731649/52814810-0f6dd180-306b-11e9-8a16-c9c6f3190a8f.jpg)
> 
> Please feel free to raise any suggestions/questions/concerns.

@gauchm For CaSPAr we will need basically all properties that were for the product. Means we also need `islive`, `type`, `ec_varname` etc.

For the product, I would handle (temporal) resolution the same as the spatial information (saved in a separate table `domain`). I would create a new table that contains all dates where the product is available. (Temporal) resolution could be quite ambiguous if time steps are missing etc.

For domain I would probably add the bounding box, i.e. min_lat, min_lon, max_lat, max_lon. Could be helpful for processing. I also can't see any projection information. I would store everything that is in the `grid_mapping` variable as a JSON string.

Product would probably have a `short_name` (used internally by us) and a `long_name` (that is human readable).

**Comment by julemai** [comment]
> Is `resolution` a feature of the product or of the variable? I.e., in a product, would all variables have the same resolution? this is probably a question from @julemai

All variables would technically have the same (temporal) resolution (at least in the NetCDF file). Some variables might just have NODATA values for the whole time step. I would assume here that we don't handle that differently. Fields containing only NODATA values in a NetCDF are not an issue memory wise. And, for example, Homa would provide all data at all time steps. Otherwise we could split them into two products.

> 
> I like the current design in that we can just "hang" additional tables off products for further customization. So GWF might not have `horizon` and `issue`.

Internally, we could still have `horizon=0` and `issue=00:00(UTC)`. 

> 
> However, another alternative design is to just combine `horizon` and `issue` into a single `product_metadata` table with`(product_id, key, value)` - i.e., you can attach any arbitrary key-value pair to any product to further define it...

Whatever you decide to be less complicated. In CaSPAr I handle static data (e.g., CaPA and RDRS) exactly the same as forecast products.

**Comment by julemai** [comment]
I'm sorry for my slow response. I am right now for a meeting in Detroit. I will be around next Tuesday morning in case you would like to meet.

**Comment by lintool** [comment]
It's likely that we'll need to iterate, so let's leave the final (v1) design up to @gauchm @YIXIN-WANG ...

**Comment by gauchm** [comment]
I tried to get some structure into addressing your comments below (let's maybe try to refer to each points number to not loose track of anything):

1. > For CaSPAr we will need basically all properties that were for the product. Means we also need `islive`, `type`, `ec_varname` etc.

Where do you think we would need `type` and `ec_varname`? In what way do you use it currently?

2. > For the product, I would handle (temporal) resolution the same as the spatial information (saved in a separate table `domain`). I would create a new table that contains all dates where the product is available. (Temporal) resolution could be quite ambiguous if time steps are missing etc.

Is your rationale for this that a product can be available from e.g. 2015-01-01 to 2018-12-12 but some dates within that range can be unavailable? 
A separate table might get pretty huge: Imagine an hourly product that's avaiable for a couple years---that's >8.7K entries per product per year... Maybe we should rather store *un*availabilities?

3. > For domain I would probably add the bounding box, i.e. min_lat, min_lon, max_lat, max_lon. Could be helpful for processing.

If we use Postgres' `polygon` data type, we get a bbox function for free: https://www.postgresql.org/docs/current/functions-geometry.html

4. > I also can't see any projection information. I would store everything that is in the `grid_mapping` variable as a JSON string.

If we store the domain as lat/lon, do we need projection information?

5. > Product would probably have a `short_name` (used internally by us) and a `long_name` (that is human readable).

That's what we intended to use `key` and `name` for.

6. > However, another alternative design is to just combine `horizon` and `issue` into a single `product_metadata` table with`(product_id, key, value)` - i.e., you can attach any arbitrary key-value pair to any product to further define it...

I tend to prefer the approach with distinct tables. It provides a more defined interface which should make handling the metadata on the UI easier.

**Comment by julemai** [comment]
1. The DB should be seen as the meta-database of the products. The variables have their origin at EC,. Nobody of these guys will know what the variables are if we don't store the `ec_varname`, `level`, etc. You won't need it to process user requests. But it is part of the variables properties.

2. You are certainly right. Maybe (temporal) resolution is indeed the most elegant way. Just make sure you call it `temporal_resolution` to not confuse it with the spatial resolution.

3. Awesome. That's great.

4. We absolutely need that. The projection is what makes the whole computation of the 2D lat/lon fields. It is much more computationally efficient to derive the grids from the projection and not from the 2D grids. Most of the programs (e.g., panoply) actually uses that variable. The projection also contains information like "equal area" etc. which you can directly access from the lat-lon fields.

5. I see. Perfect!

6. Ok. I trust you. I hope we will never get forecast products in GWF....

**Comment by gauchm** [comment]
1\. Okay, I'll include it in the variables table. 
2\. Good point, will rename it.
4\. Okay, we can include projection information. I'm not an expert in this, but I've seen three CRS identifiers: EPSG codes, PROJ.4 and WKT. Could we use one of these as a concise, well-known format to store the projection? Just dumping the grid variable content into json seems kind of shaky to me...

**Comment by julemai** [comment]
4. Nope. Because every projection has different attributes. The CaSPAr ones (so far) all look like:

```
	float rotated_pole ;
		rotated_pole:long_name = "coordinates of the rotated North Pole" ;
		rotated_pole:grid_mapping_name = "rotated_latitude_longitude" ;
		rotated_pole:earth_radius = 6371220.f ;
		rotated_pole:grid_north_pole_latitude = 31.75832f ;
		rotated_pole:grid_north_pole_longitude = 87.59703f ;
		rotated_pole:north_pole_grid_longitude = 0.f ;
		rotated_pole:longitude_of_prime_meridian = 0.f ;
```

**Comment by gauchm** [comment]
But shouldn't there be a WKT/PROJ.4/EPSG expression for exactly this? I'm not saying we only use one WKT for all products. I just want to store a WKT instead of arbitrary json for each projection.

**Comment by julemai** [comment]
Here is the standard how projections need to be incorporated in a NetCDF following the CF standard. no WKT/PROJ4/ whatsoever is required.

http://cfconventions.org/Data/cf-conventions/cf-conventions-1.0/build/ch05s06.html

**Comment by gauchm** [comment]
I see, so this is standardized in itself. Then I'm fine with storing this representation. Thanks for clarifying!

**Comment by gauchm** [comment]
Updated schema design:
![cuizinart-db](https://user-images.githubusercontent.com/15731649/52857933-afbd0800-30f6-11e9-9904-26a3aa7cd3cc.jpg)

**Comment by julemai** [comment]
Nice! The level is not necessarily an integer. I would assign it a string to allow for all current options: Geopotential height, category, or height in m/cm/mm.

**Comment by gauchm** [comment]
> Nice! The level is not necessarily an integer. I would assign it a string to allow for all current options: Geopotential height, category, or height in m/cm/mm.

Fixed (changed to string)

**Comment by YIXIN-WANG** [comment]
Updated database schema:
![image](https://user-images.githubusercontent.com/43051742/54848980-28485300-4cb9-11e9-8cfd-92ca884bd742.png)

**Comment by gauchm** [comment]
Updated DB schema with #70:
![cuizinart-db](https://user-images.githubusercontent.com/15731649/57021634-a1ed2e00-6be1-11e9-9351-096978b3d161.png)

**Comment by lintool** [comment]
I think we should create a `docs/` directory in the repo and start checking this in?
Issue can probably be closed?

**Comment by gauchm** [comment]
Good idea. I'll check it in later

**Comment by gauchm** [comment]
Created `docs/` with #72
