### ISSUE TITLE
Take a look at DataONE project

### ISSUE THREAD

**Issue by paopao74cn** [gwf-uwaterloo/cuizinart#90]
Homepage: https://www.dataone.org/ 
About DataONE: https://www.dataone.org/about 
Current Member Nodes: https://www.dataone.org/current-member-nodes#uploads 
Resources: https://www.dataone.org/resources 
Best Practices: https://www.dataone.org/best-practices

**Comment by gauchm** [comment]
Cleanup -- closing as inactive.
