### ISSUE TITLE
Take a look at SKOPE project

### ISSUE THREAD

**Issue by paopao74cn** [gwf-uwaterloo/cuizinart#91]
Homepage: https://www.openskope.org/ 
SKOPE App: https://app.openskope.org/app/discover 
Check out the Graph View feature for visualization: https://app.openskope.org/app/workspace?dataset=living-blended-drought-atlas-lbda-version-2&q=%7B%7D

**Comment by paopao74cn** [comment]
SKOPE GitHub repo: https://github.com/openskope

**Comment by gauchm** [comment]
Cleanup -- closing as inactive
