### ISSUE TITLE
Unify look and feel across Cuizinart and Wamadex

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/cuizinart#93]
Currently, Cuizinart and Wamadex have a different look and feel. Cuizinart has a floating box that is collapsible but not resizeable. Wamdex uses a split window that is resizeable but not collapsible. The UIs should be made consistent.

I personally prefer the Wamdex look and feel; so my concrete proposal is to modify Cuizinart to adopt Wamdex UI elements. And make both collapsible.

Thoughts? @gauchm @bhaleka @julemai @Alex-Weatherhead

**Comment by gauchm** [comment]
For the resizable sidebar: In Wamedex we use jQuery for this. I don't think it's a good idea to mix jQuery and React in Cuizinart.
Maybe one of these react components might help: https://github.com/STRML/react-resizable, https://github.com/bokuweb/react-rnd

**Comment by Alex-Weatherhead** [comment]
Going to close this for now. Feel free to re-open if you want any additional tweaks.
