### ISSUE TITLE
Prettier map tiles?

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/cuizinart#94]
Are there prettier map tiles we can use than the current one?

**Comment by gauchm** [comment]
There's lots to choose from: https://leaflet-extras.github.io/leaflet-providers/preview/
But: Each tile provider has their own terms of use/pricing, so we need to be careful when selecting.

**Comment by lintool** [comment]
Ones I like:

+ https://leaflet-extras.github.io/leaflet-providers/preview/#filter=Wikimedia
+ https://leaflet-extras.github.io/leaflet-providers/preview/#filter=Esri.WorldPhysical

Thoughts?

**Comment by gauchm** [comment]
For geoscientists, Esri.WorldPhysical is probably better than one with political borders. But it doesn't have labels which makes orientation quite hard.
https://leaflet-extras.github.io/leaflet-providers/preview/index.html#filter=Esri.WorldTopoMap has labels but I don't think it's prettier than what we're using now.
Generally for ESRI tiles: We need an account, but as long as we remain under 1M tile requests/month it's free. (A bit of a clash with everything else we use being fully open-source though)

**Comment by julemai** [comment]
Not sure if we should get into anything from Esri (=ArcGIS). It will cost something at one point... One decision we regret with CaSPAr.

**Comment by lintool** [comment]
Ah, I see... didn't know that Esri (=ArcGIS) @julemai 

@gauchm is the Wikimedia one free? I think it looks better than the one we have now?

**Comment by gauchm** [comment]
I think it is (https://foundation.wikimedia.org/wiki/Maps_Terms_of_Use).

Switching to the other tiles should just be a matter of changing this line: https://github.com/gwf-uwaterloo/cuizinart/blob/master/cuizinart/frontend/src/components/map.jsx#L19 to https://maps.wikimedia.org/osm-intl/${z}/${x}/${y}.png and changing the attribution message in the line below.
