### ISSUE TITLE
Exploratory look into Lucene for indexing lots of bounding boxes

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/cuizinart#98]
Let's prepare a file that has a bunch of bounding boxes (corresponding to a NetCDF file) + time range... extract this from Graham, and we try throwing it at Lucene to get a sense of performance, etc.

**Comment by lintool** [comment]
A few resources: 

https://github.com/apache/lucene-solr/blob/master/lucene/spatial-extras/src/test/org/apache/lucene/spatial/SpatialExample.java

https://lucene.apache.org/core/7_6_0/sandbox/org/apache/lucene/document/LatLonBoundingBox.html

**Comment by gauchm** [comment]
Cleanup -- closing as inactive.
